name: Deploying app on Render

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  install_dep:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: my-brand-backend

      - name: Install all dependencies
        run: npm install
        working-directory: my-brand-backend
          
  build_app:
    needs: install_dep
    runs-on: ubuntu-latest
    steps:
      - name: Running build command
        working-directory: my-brand-backend
        run: npm run build

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: soleil00/my-brand-backend


  #deploy_app_on_render:
  #  needs: build_app
 #   runs-on: ubuntu-latest
  #  steps:
  #    - name: Deploy to Render
  #      run: |
  #        curl -X POST -H "Content-Type: application/json" -d '{"branch": "main", "public": true}' https://api.render.com/deploy/srv-cnt7f4acn0vc73evu8cg?key=D4J_OGegb1Y

   #   - name: Start server
   #     run: cd dist/server && node index.js
