name: My brand ci/cd

on:
  pull_request:
    branches:
      - main
      - main-2
  push:
    branches:
      - main
      - main-2

jobs:
  checkout_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  setup_node_version:
    needs: checkout_code
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

  install_dependencies:
   needs: setup_node_version
   runs-on: ubuntu-latest

   steps:
    - name: Installing dependencies
      run: npm install

  running_tests:
   needs: install_dependencies
   runs-on: ubuntu-latest

   steps:
    - name: Running tests
      run: npm run test

  build_project:
   needs: running_tests
   runs-on: ubuntu-latest

   steps:
    - name: Building project
      run: npm run build

  
