name: Deploying app on Render

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  install_dep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm install

  build_app:
    needs: install_dep
    runs-on: ubuntu-latest
    steps:
      - name: Running build command
        run: npm run build

  deploy_app_on_render:
    needs: build_app
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"branch": "main", "public": true}' https://api.render.com/deploy/srv-cnt7f4acn0vc73evu8cg?key=D4J_OGegb1Y

      - name: Start server
        run: cd dist/server && node index.js
