name: My brand ci
name: My brand ci

on:
  pull_request:
    branches:
      - main
      - main-2
    branches:
      - main
      - main-2
  push:
    branches:
      - main
      - main-2
    branches:
      - main
      - main-2

jobs:
  build:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  

      - name: Install dependencies
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build app
      - name: Run tests
        run: npm test

      - name: Build app
        run: npm run build
