name: Deploying app on Render

on:
  pull_request:
    branches: [main, main-2]
  push:
    branches: [main, main-2]

jobs:
  install_dep:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install all dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build app
        run: npm run build
          
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: soleil00/my-brand-backend

